# Dependency Review Action
#
# This Action will scan dependency manifest files that change as part of a Pull Request, surfacing known-vulnerable versions of the packages declared or updated in the PR. Once installed, if the workflow run is marked as required, PRs introducing known-vulnerable packages will be blocked from merging.
#
# Source repository: https://github.com/actions/dependency-review-action
# Public documentation: https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/about-dependency-review#dependency-review-enforcement
name: 'Dependency Review'
on: [pull_request]

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v2
      - name: Coveralls Python
        # You may pin to the exact commit or the version.
        # uses: AndreMiras/coveralls-python-action@f5fd5c309b39d01599fb92c72d4f7409ea78aec9
        uses: AndreMiras/coveralls-python-action@v20201129
        with:
          # The `GITHUB_TOKEN` or `COVERALLS_REPO_TOKEN`.
          #github-token: # optional, default is ${{ github.token }}
          # Set to true if you are using parallel jobs, then use `parallel-finished: true` for the last action.
          parallel: true # optional
          # Set to true for the last action when using `parallel: true`.
          #parallel-finished: # optional
          # The name of a sub-directory in which the coverage files are to be found.
          #base-path: # optional
          # A description of the current job used in connection with parallel.
          flag-name: CP_sec # optional
          # Set to `true` to increase logger verbosity.
          debug: true # optional
      - name: Readme Pytest Report
        # You may pin to the exact commit or the version.
        # uses: antonin-alves/Readme-Pytest-Report@79e05665d2dffa57d36af166bf2eaddfa2b73f4f
        uses: antonin-alves/Readme-Pytest-Report@testing_0.0.6
        #with:
          # github username
          #username: # default is 
          # github user token
          #user-token: # default is 
          # github repo
          #repo: # default is 
          # github repo branch
          #branch: # default is 
